'use client'

import { useEffect, useState } from 'react'
import { useTheme } from 'next-themes'

/**
 * Shared data + theme plumbing for the homepage.
 *
 * The homepage draws every documented business as a dot on a canvas and
 * animates them through 1900-1945. The compact dataset is generated by
 * scripts/generate-homepage-points.mjs into /data/homepage-points.json.
 */

export const GRID_SIZE = 4095

/** width : height of the clipped Berlin extent (lng span * cos(lat) vs lat span) */
export const MAP_ASPECT = 1.27

/** [x, y, startYear, endYear] — x/y quantized to 0..GRID_SIZE, y from the top */
export type HomepagePoint = [number, number, number, number]

export interface HomepagePointsData {
  bounds: [number, number, number, number]
  years: [number, number]
  total: number
  plotted: number
  closingsByYear: Record<string, number>
  points: HomepagePoint[]
}

export function useHomepagePoints(): HomepagePointsData | null {
  const [data, setData] = useState<HomepagePointsData | null>(null)

  useEffect(() => {
    let cancelled = false
    fetch('/data/homepage-points.json')
      .then((res) => (res.ok ? res.json() : null))
      .then((json) => {
        if (!cancelled && json && Array.isArray(json.points)) {
          setData(json as HomepagePointsData)
        }
      })
      .catch(() => {
        // The hero degrades gracefully to its gradient background.
      })
    return () => {
      cancelled = true
    }
  }, [])

  return data
}

export type DotState = 'future' | 'active' | 'declining' | 'closed'

/** Mirrors getBusinessState in src/utils/dateHelpers.ts: declining = final 2 years */
export function dotStateForYear(year: number, start: number, end: number): DotState {
  if (year < start) return 'future'
  if (year >= end) return 'closed'
  if (year >= end - 2) return 'declining'
  return 'active'
}

export interface StateCounts {
  active: number
  declining: number
  closed: number
}

export function countStates(points: HomepagePoint[], year: number): StateCounts {
  const counts: StateCounts = { active: 0, declining: 0, closed: 0 }
  for (let i = 0; i < points.length; i++) {
    const state = dotStateForYear(year, points[i][2], points[i][3])
    if (state !== 'future') counts[state]++
  }
  return counts
}

export interface ThemeColors {
  active: string
  declining: string
  closed: string
  future: string
  foreground: string
}

/** Moody-theme values, used until the client can read the real CSS variables */
const FALLBACK_COLORS: ThemeColors = {
  active: '#97d8c0',
  declining: '#ffcb51',
  closed: '#ee5760',
  future: '#6b6275',
  foreground: '#f5cdb4',
}

/**
 * Reads the state colors from the active theme's CSS variables so the canvas
 * stays in sync with theme switching (canvas cannot use var() directly).
 */
export function useThemeColors(): ThemeColors {
  const { theme } = useTheme()
  const [colors, setColors] = useState<ThemeColors>(FALLBACK_COLORS)

  useEffect(() => {
    const style = getComputedStyle(document.documentElement)
    const read = (name: string, fallback: string) => style.getPropertyValue(name).trim() || fallback
    setColors({
      active: read('--success', FALLBACK_COLORS.active),
      declining: read('--warning', FALLBACK_COLORS.declining),
      closed: read('--danger', FALLBACK_COLORS.closed),
      future: read('--muted', FALLBACK_COLORS.future),
      foreground: read('--foreground', FALLBACK_COLORS.foreground),
    })
  }, [theme])

  return colors
}

/** Locale-aware thousands separators for the stat displays */
export function formatCount(value: number, language: string): string {
  try {
    return new Intl.NumberFormat(language === 'de' ? 'de-DE' : 'en-US').format(value)
  } catch {
    return String(value)
  }
}
